-- ============================================================================
-- SunuRecolte — Migration V1 : schéma initial
-- ----------------------------------------------------------------------------
-- Reproduit fidèlement le modèle JPA (9 entités) validé dans ARCHITECTURE.md.
-- Cible : PostgreSQL, base "sunurecolte".
-- Au démarrage, Hibernate vérifie ce schéma en lecture seule (ddl-auto=validate)
-- et ne crée plus aucune table : toute évolution passe par une nouvelle
-- migration versionnée (V2__..., V3__...). Ne pas modifier ce fichier une fois
-- appliqué.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- utilisateurs
-- ----------------------------------------------------------------------------
CREATE TABLE utilisateurs (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    nom           varchar(100) NOT NULL,
    prenom        varchar(100) NOT NULL,
    email         varchar(150) NOT NULL,
    telephone     varchar(20)  NOT NULL,
    mot_de_passe  varchar(255) NOT NULL,
    role          varchar(20)  NOT NULL,
    date_creation timestamp(6) NOT NULL,
    actif         boolean      NOT NULL,
    CONSTRAINT pk_utilisateurs PRIMARY KEY (id),
    CONSTRAINT uq_utilisateurs_email UNIQUE (email),
    CONSTRAINT ck_utilisateurs_role CHECK (role IN ('PRODUCTEUR', 'ACHETEUR', 'ADMIN'))
);

-- ----------------------------------------------------------------------------
-- producteurs (profil lié à utilisateurs, relation 1-1)
-- ----------------------------------------------------------------------------
CREATE TABLE producteurs (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY,
    utilisateur_id            bigint       NOT NULL,
    localisation_exploitation varchar(255),
    filiere                   varchar(20)  NOT NULL,
    description               text,
    CONSTRAINT pk_producteurs PRIMARY KEY (id),
    CONSTRAINT uq_producteurs_utilisateur UNIQUE (utilisateur_id),
    CONSTRAINT fk_producteurs_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id),
    CONSTRAINT ck_producteurs_filiere CHECK (filiere IN ('MARAICHAGE', 'ELEVAGE', 'CEREALES', 'AUTRE'))
);

-- ----------------------------------------------------------------------------
-- acheteurs (profil lié à utilisateurs, relation 1-1)
-- ----------------------------------------------------------------------------
CREATE TABLE acheteurs (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    utilisateur_id bigint      NOT NULL,
    type_acheteur  varchar(20) NOT NULL,
    CONSTRAINT pk_acheteurs PRIMARY KEY (id),
    CONSTRAINT uq_acheteurs_utilisateur UNIQUE (utilisateur_id),
    CONSTRAINT fk_acheteurs_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id),
    CONSTRAINT ck_acheteurs_type CHECK (type_acheteur IN ('COMMERCANT', 'RESTAURATEUR', 'PARTICULIER'))
);

-- ----------------------------------------------------------------------------
-- recoltes (appartient à un producteur)
-- ----------------------------------------------------------------------------
CREATE TABLE recoltes (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    producteur_id       bigint        NOT NULL,
    produit             varchar(150)  NOT NULL,
    description         text,
    quantite_disponible numeric(10,2) NOT NULL,
    quantite_min        numeric(10,2),
    quantite_max        numeric(10,2),
    unite               varchar(30)   NOT NULL,
    prix_unitaire       numeric(10,2) NOT NULL,
    image_url           varchar(500),
    localisation        varchar(255),
    date_disponibilite  date,
    statut              varchar(20)   NOT NULL,
    date_creation       timestamp(6)  NOT NULL,
    CONSTRAINT pk_recoltes PRIMARY KEY (id),
    CONSTRAINT fk_recoltes_producteur FOREIGN KEY (producteur_id) REFERENCES producteurs (id),
    CONSTRAINT ck_recoltes_statut CHECK (statut IN ('DISPONIBLE', 'EPUISEE'))
);

CREATE INDEX idx_recoltes_producteur_id ON recoltes (producteur_id);

-- ----------------------------------------------------------------------------
-- commandes (passée par un acheteur)
-- ----------------------------------------------------------------------------
CREATE TABLE commandes (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY,
    acheteur_id            bigint        NOT NULL,
    date_creation          timestamp(6)  NOT NULL,
    statut                 varchar(20)   NOT NULL,
    total                  numeric(12,2) NOT NULL,
    mode_reception         varchar(20)   NOT NULL,
    adresse_livraison      varchar(255),
    telephone_livraison    varchar(20),
    instructions_livraison text,
    CONSTRAINT pk_commandes PRIMARY KEY (id),
    CONSTRAINT fk_commandes_acheteur FOREIGN KEY (acheteur_id) REFERENCES acheteurs (id),
    CONSTRAINT ck_commandes_statut CHECK (statut IN ('EN_ATTENTE', 'CONFIRMEE', 'PRETE', 'LIVREE', 'ANNULEE')),
    CONSTRAINT ck_commandes_mode_reception CHECK (mode_reception IN ('RETRAIT', 'LIVRAISON'))
);

CREATE INDEX idx_commandes_acheteur_id ON commandes (acheteur_id);

-- ----------------------------------------------------------------------------
-- lignes_commande (associe une récolte à une commande ; prix_unitaire = prix
-- historique au moment de la commande)
-- ----------------------------------------------------------------------------
CREATE TABLE lignes_commande (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    commande_id   bigint        NOT NULL,
    recolte_id    bigint        NOT NULL,
    quantite      numeric(10,2) NOT NULL,
    prix_unitaire numeric(10,2) NOT NULL,
    sous_total    numeric(12,2) NOT NULL,
    CONSTRAINT pk_lignes_commande PRIMARY KEY (id),
    CONSTRAINT fk_lignes_commande_commande FOREIGN KEY (commande_id) REFERENCES commandes (id),
    CONSTRAINT fk_lignes_commande_recolte FOREIGN KEY (recolte_id) REFERENCES recoltes (id)
);

CREATE INDEX idx_lignes_commande_commande_id ON lignes_commande (commande_id);
CREATE INDEX idx_lignes_commande_recolte_id ON lignes_commande (recolte_id);

-- ----------------------------------------------------------------------------
-- paiements (un paiement par commande)
-- ----------------------------------------------------------------------------
CREATE TABLE paiements (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    commande_id           bigint        NOT NULL,
    reference_transaction varchar(100),
    montant               numeric(12,2) NOT NULL,
    moyen_paiement        varchar(20)   NOT NULL,
    statut                varchar(20)   NOT NULL,
    date_creation         timestamp(6)  NOT NULL,
    date_confirmation     timestamp(6),
    CONSTRAINT pk_paiements PRIMARY KEY (id),
    CONSTRAINT uq_paiements_commande UNIQUE (commande_id),
    CONSTRAINT fk_paiements_commande FOREIGN KEY (commande_id) REFERENCES commandes (id),
    CONSTRAINT ck_paiements_moyen CHECK (moyen_paiement IN ('WAVE', 'ORANGE_MONEY')),
    CONSTRAINT ck_paiements_statut CHECK (statut IN ('EN_ATTENTE', 'REUSSI', 'ECHOUE', 'ANNULE'))
);

-- ----------------------------------------------------------------------------
-- notifications (destinataire : utilisateur)
-- ----------------------------------------------------------------------------
CREATE TABLE notifications (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    utilisateur_id bigint       NOT NULL,
    titre          varchar(200) NOT NULL,
    message        text         NOT NULL,
    lu             boolean      NOT NULL,
    date_creation  timestamp(6) NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id)
);

CREATE INDEX idx_notifications_utilisateur_id ON notifications (utilisateur_id);

-- ----------------------------------------------------------------------------
-- prix_marche (prix indicatifs administrés, sans lien avec recoltes)
-- ----------------------------------------------------------------------------
CREATE TABLE prix_marche (
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    produit          varchar(150)  NOT NULL,
    unite            varchar(30)   NOT NULL,
    prix_moyen       numeric(10,2) NOT NULL,
    marche_reference varchar(150),
    date_mise_a_jour timestamp(6)  NOT NULL,
    CONSTRAINT pk_prix_marche PRIMARY KEY (id)
);
